Exposed more functions in FieldDescriptor and OneofDescriptor.
protocolbuffers/protobuf pull request #10102
Opened 2022-06-02 15:19 UTC by fiboknacky

### FieldDescriptor

- Added support for `getContainingOneof` and `getRealContainingOneof`.
- Added support for setting proto3 optional (internal only).
- Remove the unused private var.

### OneofDescriptor

- Made `isSynthetic` work.

2022-06-02 16:30 UTC, haberman requested changes

2022-06-03 07:52 UTC, fiboknacky commented on php/src/Google/Protobuf/FieldDescriptor.php
> -    public function hasOptionalKeyword()
I'll leave it here for now, but it's broken code.
Looks like the C++ implementation needs to rely on many things that don't exist yet. I'll leave this function to you.

2022-06-09 07:56 UTC, fiboknacky commented on php/src/Google/Protobuf/Internal/FieldDescriptor.php
> -            lcfirst(implode('', array_map('ucwords', explode('_', $proto->getName()))));
This is redundant with the if clause below.

2022-06-13 03:49 UTC, haberman approved these changes

2022-06-13 03:49 UTC, merged