Issue #10198: Utility func in FieldMaskUtil.java to clear fields specified in FieldMask
protocolbuffers/protobuf pull request #10242
Opened 2022-07-11 18:21 UTC by selotape

Hi,

I implemented a simple function on FieldMaskUtil to _clear_ the fields specified in the mask instead of "copy only these fields", as described in Issue #10198.

For this, I extended the existing recursive `FieldMaskTree.merge()` method using a `MergeOption.clearField`. This is of course covered by tests I deemed relevant.

I'm not 100% confident about my choice of method names, nor about any performance/waste issues in `destination.mergeFrom(source)`, nor about my decision to reuse and extend `FieldMaskTree.merge()` rather than copy+pasting+editing it.

I'd love to hear your thoughts.

Thanks!

2022-07-22 18:07 UTC, selotape commented
Hey, can I help in any way? Maybe schedule a short VC with the reviewer to explain the changes so it's easier to review?

2022-08-12 17:37 UTC, shaod2 commented
Hi selotape, thanks for you contribution and sorry for the delay.

This is a sound PR. We're still evaluating it and its implication to other protobuf languages from our internal codebase.

2022-08-14 09:41 UTC, selotape commented
Thank you!

I'd love to extend this CL as you think is needed (within my abilities).

Looking forward to news from you.

2022-08-24 18:04 UTC, selotape commented
Hey, any news? Thanks!

2022-08-24 19:50 UTC, shaod2 commented
After having a closer look over our fieldmask API, doesn't `trim()` meet what you want? I know there's definitely a reason for "clearing" instead of "trimming", but just want to make sure that method was considered. Can you justify it with your use case?

2022-08-25 17:48 UTC, selotape commented
Sure, using `trim()` is a possibility. It means I'll create+maintain a long list of all the ""whitelisted"" fields my consumers care about.
This is certainly valid and more secure, but I think less suitable for me because:
* I'm sharing data with trusted backend services. I prefer the faster development, easier maintanence and "future-proofing" of a black list. 
* The proto I'm sharing is large and nested and I'm presently not even sure of all fields my consumers care about. I am however sure of the large/costly fields I'd rather not share.
* For me this is "just" a traffic/bandwidth optimization. Even if I accidentally send a fields that's large, it's not critical and will fix it when an issue is detected.

So a list of "these fields should be deleted" is more suitable for my situation

2022-09-01 12:13 UTC, selotape commented
Any thoughts shaod2?

2022-09-07 22:29 UTC, shaod2 commented
I've started a proposal but currently interrupted by some other tasks. I hope I can send it for review this week

2022-09-20 21:12 UTC, shaod2 requested changes

2022-09-20 21:12 UTC, shaod2 commented on java/util/src/main/java/com/google/protobuf/util/FieldMaskTree.java
> +  void mergeClearing(Message source, Message.Builder destination) {
"mergeClear"

2022-09-20 21:14 UTC, shaod2 commented
Hi sorry for the delay. Proposal is approved. Let's work on the PR now. We don't have to worry about other languages for now

2022-09-22 10:33 UTC, selotape commented on java/util/src/main/java/com/google/protobuf/util/FieldMaskTree.java
> +  void mergeClearing(Message source, Message.Builder destination) {
Done

2022-09-22 10:33 UTC, selotape commented on java/util/src/test/java/com/google/protobuf/util/FieldMaskTreeTest.java
> +  public void testClear() {
Done

2022-09-22 10:38 UTC, selotape commented on java/util/src/main/java/com/google/protobuf/util/FieldMaskTree.java
> +   * Merges all fields specified by this FieldMaskTree from {@code source} to {@code destination}.
Thanks,
I added the missing information. PTAL

2022-09-26 18:55 UTC, selotape commented
Hey shaod2, please see my fixes

2022-10-03 07:07 UTC, selotape commented
Hey  @shaod2 , anything else you think needs attention?

2022-10-04 16:26 UTC, shaod2 commented
Hi sorry again for the delay. Unfortunately, we have to suspend this PR until further notice.

Protobuf is dealing with some ownership issues about the FieldMask API. Google has officially built up [Google API Improvement Proposals](https://google.aip.dev/), which contains some approved proposals for FieldMask, but most of these proposals diverge from Protobuf and historically, updates to FieldMask libraries have caused confusions and inconsistency. Therefore, we are resolving this unclear ownership and stop any updates to it.

2022-10-04 16:26 UTC, closed without merging