[Mac] Support bazelisk and drop -j argument.
protocolbuffers/protobuf pull request #10412
Opened 2022-08-15 17:50 UTC by thomasvl

The support for -j was there since make didn't do parallel builds by default.

2022-08-15 17:54 UTC, mkruskal-google commented
This LGTM but Kokoro is currently down, so let's wait till that actually runs

2022-08-15 17:54 UTC, mkruskal-google requested changes
This LGTM but Kokoro is currently down, so let's wait till that actually runs

2022-08-16 16:45 UTC, thomasvl commented
> This LGTM but Kokoro is currently down, so let's wait till that actually runs

Ok, got a full kokoro run, so I think it is likely ready for complete review.

2022-08-16 17:10 UTC, mkruskal-google approved these changes

2022-08-16 17:12 UTC, merged