doc: Add documentation for CMake `protobuf_generate`
protocolbuffers/protobuf pull request #10590
Opened 2022-09-15 18:48 UTC by Tradias

How to use it.
How it works. (basic example and an example with gRPC)
Reference documentation.

Resolves https://github.com/protocolbuffers/protobuf/issues/10303

2022-09-27 21:12 UTC, Logofile requested changes

2022-09-27 21:12 UTC, Logofile commented on docs/cmake_protobuf_generate.md
> +And `protoc` will automatically be re-run whenever the schema files change and `proto-objects` is build.
"...is built."

2022-09-27 21:12 UTC, Logofile commented on docs/cmake_protobuf_generate.md
> +- `EXPORT_MACRO` — Name of a macro that is applied to all generated Protobuf message classes and extern variables. It can e.g. be used to declare DLL exports.
"It can, for example, be used to..."

2022-09-27 21:12 UTC, Logofile commented on docs/cmake_protobuf_generate.md
> +- `PROTOC_OUT_DIR` — Output directory of generated source files, defaults to `CMAKE_CURRENT_BINARY_DIR`.
"...source files. Defaults to..."

2022-09-27 21:12 UTC, Logofile commented on docs/cmake_protobuf_generate.md
> +- `PLUGIN` — An optional plugin executable. This could e.g. be the path to `grpc_cpp_plugin`.
"...could, for example, be the path..."

2022-09-27 21:12 UTC, Logofile commented on docs/cmake_protobuf_generate.md
> +- `PLUGIN_OPTIONS` — Additional options provided to the plugin, e.g. `generate_mock_code=true` for the gRPC cpp plugin.
"...plugin, such as..."

2022-09-27 21:12 UTC, Logofile commented on docs/cmake_protobuf_generate.md
> +Multi value arguments:
"Multi-value"

2022-09-27 21:12 UTC, Logofile commented on docs/cmake_protobuf_generate.md
> +Single value arguments:
"Single-value"

2022-09-27 21:12 UTC, Logofile commented on docs/cmake_protobuf_generate.md
> +- `IMPORT_DIRS` — A common parent directory for the schema files. E.g., if the schema file is `proto/helloworld/helloworld.proto` and the import directory `proto/` then the generated files are `${PRO
"For example, if the schema..."

2022-09-28 11:00 UTC, Tradias commented
@Logofile I have addressed your requested changes. Thanks a lot for the review!

2022-09-29 15:49 UTC, acozzette approved these changes

2022-09-29 18:45 UTC, Logofile approved these changes

2022-09-29 18:50 UTC, merged