feat(ruby): support to call method using symbol as well in Message_index
protocolbuffers/protobuf pull request #12408
Opened 2023-04-05 06:16 UTC by bajajneha27

b/229817649

2023-04-06 21:24 UTC, haberman requested changes
Please add a test.

2023-04-06 21:24 UTC, haberman commented on ruby/ext/google/protobuf_c/message.c
> +             "Expected string or symbols as hash keys when accessing a field's "
Let's not use the word "hash" here. It implies that there is a Ruby Hash object underneath, which there is not.

I think the error message words if you just remove the word "hash."

2023-05-17 12:19 UTC, bajajneha27 commented
> Please add a test.

I added a test. I'm not sure about the reasons of failure. Can someone from your team help me out here?

2023-09-11 14:24 UTC, JasonLunn commented
@bajajneha27 - can you merge `main` into your branch? I went to go look at the failing logs but they're no longer available.

2023-09-13 08:48 UTC, bajajneha27 commented
> @bajajneha27 - can you merge `main` into your branch? I went to go look at the failing logs but they're no longer available.

Done. Thanks for looking  into it.

2023-09-13 13:50 UTC, JasonLunn commented
Ruby tests are failing with a segfault in `ruby/tests/common_tests.rb` line 901 and `ruby/compatibility_tests/v3.0.0/tests/basic.rb` line 926. Do these reproduce for you locally?

2023-09-14 11:44 UTC, bajajneha27 commented
> ruby/compatibility_tests/v3.0.0/tests/basic.rb

I see `common_test` one in my local :
```
/usr/local/google/home/bajajnehaa/gcp/protobuf/ruby/tests/common_tests.rb:901:in `test_bad_field_names'
/usr/local/google/home/bajajnehaa/gcp/protobuf/ruby/tests/common_tests.rb:901:in `[]'
```

But I don't see `basic.rb` in the error log.
I ran `rake test` to run the tests

2023-12-29 10:02 UTC, closed without merging