Updated upb version.
protocolbuffers/protobuf pull request #12834
Opened 2023-05-16 20:34 UTC by haberman

2023-05-16 20:35 UTC, mkruskal-google requested changes

2023-05-16 20:35 UTC, mkruskal-google commented on third_party/abseil-cpp
umm what happened here?

2023-05-30 09:34 UTC, hlopko commented
Is this PR still active? If not, could you please close it? Thank you!

2023-06-20 21:36 UTC, zhangskz commented
This is obsolete -- the 23.x upb version was already updated recently as part of 23.3 release.

2023-06-20 21:36 UTC, closed without merging