Migrate usages of deprecated JavaInfo fields
protocolbuffers/protobuf pull request #13830
Opened 2023-09-04 04:37 UTC by sgowroji

transitive_deps was an alias for transitive_compile_time_jars

The fields were deprecated in 2021, and are dropped in Bazel@HEAD

Fixes bazelbuild#1003

2023-09-04 04:42 UTC, sgowroji commented
[dmaclach](https://github.com/dmaclach) This  fixes the protobuf failure at Bazel@HEAD. https://github.com/protocolbuffers/protobuf/issues/13829. Not familiar with the failure testcase. Can you have a look. Thanks!

2023-09-04 09:08 UTC, meteorcloudy commented
@sgowroji I think the c++ code just happen to have similar names but it's in fact irrelevant to the breakage, you'll need to update rules_kotlin instead.

2023-09-04 09:45 UTC, sgowroji commented
Oh okay. @meteorcloudy Thanks for information.

2023-09-04 10:16 UTC, meteorcloudy requested changes

2023-09-04 10:16 UTC, meteorcloudy commented on src/google/protobuf/compiler/objectivec/file.cc
> +    transitive_deps_collector.insert(dep_info.transitive_deps.begin(),
Please revert this change.

2023-09-04 10:16 UTC, sgowroji commented on src/google/protobuf/compiler/objectivec/file.cc
> +    transitive_deps_collector.insert(dep_info.transitive_deps.begin(),
Done.

2023-09-06 05:27 UTC, sgowroji commented
Reverting this PR until there is release from rules_kotlin

2023-09-08 06:23 UTC, sgowroji commented
@meteorcloudy Can you please review. Thanks!

2023-09-08 09:15 UTC, meteorcloudy approved these changes

2023-09-11 05:23 UTC, sgowroji commented
Merged at cl/563772250

2023-09-11 05:23 UTC, closed without merging