Add back android config_setting that looks for //external:android/crosstool
protocolbuffers/protobuf pull request #16127
Opened 2024-03-11 23:11 UTC by sifmelcara

In https://github.com/protocolbuffers/protobuf/pull/15298 `"crosstool_top": "//external:android/crosstool"` was replaced with `"crosstool_top": "@platforms//os:android"`. This breaks users who have not migrated to https://bazel.build/concepts/platforms yet.

2024-03-11 23:18 UTC, sifmelcara commented
@acozzette

2024-03-12 18:20 UTC, acozzette requested changes

2024-03-12 18:56 UTC, sifmelcara commented on third_party/abseil-cpp
Fixed, thanks!

2024-03-12 19:45 UTC, acozzette approved these changes

2024-03-13 16:54 UTC, closed without merging