[7392] fix conformance test in PHP JSON parser
protocolbuffers/protobuf pull request #16743
Opened 2024-05-04 13:14 UTC by antongrbin

2024-06-24 18:24 UTC, antongrbin commented
@jskeet, since you worked with me on the linked issue https://github.com/protocolbuffers/protobuf/issues/7392, is it OK to ask you to help me find a PHP reviewer to move this forward?

2024-06-24 18:27 UTC, bshaffer commented
@antongrbin I can take a look

2024-07-08 12:50 UTC, antongrbin commented
@bshaffer thank you for the review offer && polite ping :)

2024-07-23 19:40 UTC, antongrbin commented
@bshaffer friendly ping :)

2024-10-11 20:40 UTC, bshaffer reviewed
This is really the behavior we want? If an array/map is unknown, it throws an exception unless _other_ valid values exist, at which point the unknown value is ignored? 

That does not seem like intuitive behavior to me... what is the justification for this?

2024-11-22 16:35 UTC, bshaffer requested changes

2024-11-23 15:53 UTC, antongrbin commented on php/tests/EncodeDecodeTest.php
> +          ]}",
Great catch! I now made the JSON string inputs equal in each test pair.

2024-11-23 15:54 UTC, antongrbin commented
@bshaffer thank you for your time for reviewing this and sorry for the delay.

I recently switched companies so I lost access to noom/protobuf and can't update this PR anymore.

I created a new equivalent PR here: https://github.com/protocolbuffers/protobuf/pull/19376.

2024-11-23 15:54 UTC, closed without merging