Drop duplicated `inline` qualifier
protocolbuffers/protobuf pull request #18880
Opened 2024-10-17 12:27 UTC by fmeum

This gets rid of this very noisy warning when compiling with MSVC:

```
C:\b\z46qjgck\execroot\_main\bazel-out\x64_windows-fastbuild\bin\external\protobuf+\src\google\protobuf\_virtual_includes\protobuf_lite\google/protobuf/message_lite.h(1191): warning C4141: 'inline': used more than once
C:\b\z46qjgck\execroot\_main\bazel-out\x64_windows-fastbuild\bin\external\protobuf+\src\google\protobuf\_virtual_includes\protobuf_lite\google/protobuf/message_lite.h(1297): warning C4141: 'inline': used more than once
```

2024-10-17 12:28 UTC, fmeum commented
@meteorcloudy FYI, this causes Windows logs in Bazel CI to initially overflow the Buildkite limit for streamable logs.

2024-10-17 16:57 UTC, zhangskz approved these changes

2024-10-18 16:31 UTC, zhangskz requested changes
@sbenzaquen pointed out in review that these are not duplicate since we can't mark a function always_inline if it is not inline, and tht they likely have the be in the opposite order to make MSVC happier.

2024-10-18 16:39 UTC, fmeum commented
@zhangskz Changed

2024-10-18 16:44 UTC, zhangskz commented
@sbenzaquen Can you take a look?

2024-10-18 18:18 UTC, mkruskal-google approved these changes

2024-11-19 01:23 UTC, tonyliaoss commented
@fmeum Looks like there is a merge conflict. Could you rebase? I can kick off a new round of tests afterwards.

2024-11-21 21:01 UTC, tonyliaoss commented
Actually, I think this is addressed by https://github.com/protocolbuffers/protobuf/commit/8a33e2b5bc5efc4db9c9e0a93b95bcd02f502f27. Please reopen that commit didn't resolve your issue.

2024-11-21 21:01 UTC, closed without merging