Fix failure list trie behavior
protocolbuffers/protobuf pull request #19207
Opened 2024-11-09 20:57 UTC by yamilmorales

There was no mechanism to recognize test names as prefix of another. Although it seems hard to see where this might occur in practice, this is the way that a trie **should** behave. There might be some debate of whether or not to consider these prefixes as duplicates, but I'm not completely sure. Having a hard time wrapping my head around this. Let me know what you  think whoever reviews this!

2024-11-12 16:52 UTC, mkruskal-google reviewed
Awesome, thanks Yamil!

2024-11-23 07:26 UTC, yamilmorales commented on conformance/failure_list_trie_node.cc
> +      test_name != section ? test_name.substr(section.length() + 1) : "";
Done.

2024-11-27 22:41 UTC, acozzette requested changes

2024-11-27 22:41 UTC, acozzette commented on conformance/failure_list_trie_node.cc
> +  bool name_equals_section = test_name == section;
I would suggest renaming this variable `last_section` or `is_last_section` since I think that is what we're really testing for here.

2024-11-27 22:41 UTC, acozzette commented on conformance/failure_list_trie_node.cc
> +    if (child->data_ == section && name_equals_section) {
Maybe these two if statements could be simplified a little bit by combining them like this:
```
if (child->data_ == section) {
  if (name_equals_section) {
    child->is_test_name = true;
  } else {
    child->InsertImpl(test_name_rest);
  }
  return;
}
```

2024-11-28 07:12 UTC, yamilmorales reviewed
Done.

2024-12-02 18:04 UTC, acozzette approved these changes

2024-12-03 00:31 UTC, mkruskal-google commented on conformance/failure_list_trie_node.cc
> +    if (child->data_ == section && test_name == section) {
What I meant was that you're branching on the same condition in 4 different places.  That creates potentially 2^4=16 possible paths over time as things evolve (it's hard to keep 4 things synchronized).  Sometimes it's better to branch earlier even if it creates some duplication.  For example, you could have two different InsertImpl methods for the two cases

2024-12-03 00:44 UTC, closed without merging