Update Field Presence doc
protocolbuffers/protobuf pull request #8959
Opened 2021-09-09 01:46 UTC by VeryStrongFingers

Updated information surrounding the usage of `optional` and the `--experimental_allow_proto3_optional` flag with relevant information between v3.12 & 3.15.

Since release v3.15:
>  Optional fields for proto3 are enabled by default, and no longer require
>  the --experimental_allow_proto3_optional flag.

Now the doc infers the feature is implicitly enabled, rather than an experimental flag which was only true up until v3.15.0

see notes on optional/`--experimental_allow_proto3_optional` here:
- https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0
- https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0

2021-09-09 01:51 UTC, VeryStrongFingers commented
@googlebot I signed it!

2021-09-09 16:36 UTC, haberman requested changes

2021-09-09 16:36 UTC, haberman commented on docs/field_presence.md
> +These are the general steps to u field tracking support for proto3:
I think this should be "use"?

2021-09-10 01:40 UTC, VeryStrongFingers commented on docs/field_presence.md
> +These are the general steps to u field tracking support for proto3:
Good catch. Fixed that up

2021-09-10 15:14 UTC, haberman approved these changes

2021-09-10 15:14 UTC, merged