Issue 7373
protocolbuffers/protobuf pull request #9439
Opened 2022-01-26 07:25 UTC by euggor

Generated Java code using InternalOneOfEnum should reference AbstractMessageLite instead of AbstractMessage.

java_message C++ code has been adjusted in accordance with the java interface AbstractMessageLite.

2022-01-26 07:26 UTC, euggor commented
@darly Plz review fix for https://github.com/protocolbuffers/protobuf/issues/7373

2022-01-26 07:33 UTC, euggor commented
This bug has been introduced here:

commit 4f02f056b5cea99052bfdfb6698afe47a3cf2964 Date: 8/23/19, 7:33 AM

2022-01-26 16:01 UTC, elharo requested changes
This needs a test case

2022-02-01 09:30 UTC, ygots commented
@elharo The original issue were in versions for scala 2.12.x and for `scala-maven-plugin` as well. Plz close this PR.

2022-02-02 04:12 UTC, closed without merging